/**
 * OpenAI image generation service
 * Adapted from SnapAI (https://github.com/betomoedano/snapai)
 */

import OpenAI from "openai";
import type { ImageGenerateParams } from "openai/resources/images.js";

// ════════════════════════════════════════════════════════════════════════════
// TYPES
// ════════════════════════════════════════════════════════════════════════════

export type OpenAIImageModel = "gpt-1" | "gpt-1.5";
export type ImageQuality = "auto" | "high" | "medium" | "low";
export type ImageBackground = "transparent" | "opaque" | "auto";
export type ImageOutputFormat = "png" | "jpeg" | "webp";
export type ImageSize = "1024x1024" | "1536x1024" | "1024x1536";

export interface OpenAIImageOptions {
  prompt: string;
  model?: OpenAIImageModel;
  quality?: ImageQuality;
  background?: ImageBackground;
  outputFormat?: ImageOutputFormat;
  numImages?: number;
  size?: ImageSize;
}

// ════════════════════════════════════════════════════════════════════════════
// SERVICE
// ════════════════════════════════════════════════════════════════════════════

/**
 * Model alias → OpenAI model ID mapping
 */
const MODEL_MAP: Record<string, string> = {
  "gpt-1": "gpt-image-1",
  "gpt-1.5": "gpt-image-1.5",
};

function getClient(): OpenAI {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "OpenAI API key not configured.\n" +
      "Set the OPENAI_API_KEY environment variable to use OpenAI image generation."
    );
  }
  return new OpenAI({ apiKey });
}

function resolveModelId(alias: string): string {
  return MODEL_MAP[alias] || alias;
}

function mapQualityForGptImage1(quality: string): string {
  const qualityMap: Record<string, string> = {
    auto: "auto",
    high: "high",
    medium: "medium",
    low: "low",
  };
  return qualityMap[quality] || "auto";
}

/**
 * Generate images using OpenAI's image API.
 * Returns an array of base64-encoded image strings.
 */
export async function generateWithOpenAI(options: OpenAIImageOptions): Promise<string[]> {
  const client = getClient();
  const {
    prompt,
    model = "gpt-1.5",
    quality = "auto",
    background = "auto",
    outputFormat = "png",
    numImages = 1,
    size = "1024x1024",
  } = options;

  const resolvedModelId = resolveModelId(model);
  const isGptImage1 = resolvedModelId === "gpt-image-1";

  // Build request params
  const requestParams: Record<string, unknown> = {
    model: resolvedModelId,
    prompt,
    n: numImages,
    size,
    response_format: "b64_json",
  };

  // gpt-image-1 specific params
  if (isGptImage1) {
    requestParams.quality = mapQualityForGptImage1(quality);
    requestParams.background = background;
    requestParams.output_format = outputFormat;
    requestParams.moderation = "auto";
  }

  const response = await client.images.generate(requestParams as unknown as ImageGenerateParams);

  const images: string[] = [];
  const data = (response as unknown as { data?: Array<{ b64_json?: string }> }).data;
  for (const item of data || []) {
    if (item.b64_json) {
      images.push(item.b64_json);
    }
  }

  if (images.length === 0) {
    throw new Error("No images were generated by OpenAI");
  }

  return images;
}

/**
 * Check if an OpenAI API key is available in the environment.
 */
export function isOpenAIAvailable(): boolean {
  return !!process.env.OPENAI_API_KEY;
}
